/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{tsx,jsx,js,ts}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        // Tipografía sin definir todavía: se usa la del sistema.
        sans: ["ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        rounded: ["SF Pro Rounded", "Hiragino Maru Gothic ProN", "Meiryo", "MS PGothic", "sans-serif"],
        serif: ["Georgia", "Times New Roman", "serif"],
      },
      colors: {
        primary: {
          DEFAULT: "#a78bfa",
          hover: "#c4b5fd",
          container: "#2e1065",
          "on-primary": "#09090b",
          "on-primary-container": "#ddd6fe",
          "inverse-primary": "#a78bfa",
          fixed: "#eaddff",
          "fixed-dim": "#d2bbff",
          "on-fixed": "#25005a",
          "on-fixed-variant": "#5a00c6",
        },
        surface: {
          DEFAULT: "#0c0c0f",
          dim: "#0a0a0e",
          bright: "#131318",
          card: "#16171f",
          "container-lowest": "#09090b",
          "container-low": "#0f1017",
          "container": "#16171f",
          "container-high": "#1f202b",
          "container-highest": "#27272a",
          elevated: "#222433",
          secondary: "#1e1f2b",
          border: "#27272a",
          variant: "#2f2f37",
          tint: "#a78bfa",
          inverse: "#e8e8f0",
          "inverse-on": "#1a1a22",
        },
        text: {
          primary: "#fafafa",
          secondary: "#a1a1aa",
          tertiary: "#71717a",
        },
        outline: {
          DEFAULT: "#52525b",
          variant: "#27272a",
        },
        background: "#09090b",
        "on-background": "#fafafa",
        success: {
          DEFAULT: "#34d399",
          container: "#064e3b",
        },
        warning: {
          DEFAULT: "#fbbf24",
          container: "#78350f",
        },
        danger: {
          DEFAULT: "#ef4444",
          container: "#7f1d1d",
        },
        info: {
          DEFAULT: "#38bdf8",
          container: "#0c4a6e",
        },
        secondary: {
          DEFAULT: "#bec6e0",
          container: "#3e465b",
          "on-secondary": "#272e42",
          "on-secondary-container": "#dae2fc",
          fixed: "#dae2fc",
          "fixed-dim": "#bec6e0",
          "on-fixed": "#131b2e",
          "on-fixed-variant": "#3e465b",
        },
        tertiary: {
          DEFAULT: "#92ccff",
          container: "#004b73",
          "on-tertiary": "#003351",
          "on-tertiary-container": "#cce5ff",
          fixed: "#cce5ff",
          "fixed-dim": "#92ccff",
          "on-fixed": "#001d31",
          "on-fixed-variant": "#004b73",
        },
        error: {
          DEFAULT: "#ef4444",
          container: "#450a0a",
          "on-error": "#7f1d1d",
          "on-error-container": "#ffe4e6",
        },
        "on-surface": "#fafafa",
        "on-surface-variant": "#a1a1aa",
      },
      // Escala tipográfica en px (no rem): en nativo `rem` depende de la base
      // del runtime y termina siendo frágil. 11px es el mínimo legible;
      // 16px es el cuerpo estándar.
      fontSize: {
        "2xs": ["11px", { lineHeight: "14px" }],
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "22px" }],
        lg: ["18px", { lineHeight: "24px" }],
        xl: ["20px", { lineHeight: "26px" }],
        "2xl": ["24px", { lineHeight: "30px" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        margin: "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
    },
  },
  plugins: [],
};
